default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: basketball_courts_development
  username: nkk0508
  password: vcdunk15

test:
  <<: *default
  database: basketball_courts_test
  username: nkk0508
  password: vcdunk15

production:
  <<: *default
  database: basketball_courts_production
  username: nkk0508
  password: vcdunk15