default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DB_NAME'] %>_development
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>

test:
  <<: *default
  database: <%= ENV['DB_NAME'] %>_test
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>_production
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>